### ISSUE TITLE
Testing testing/Naz

### ISSUE THREAD

**Issue by nazaninpouresmaili** [pernilla-hallgren/github-test#4]
# My first Issue
## With some Markdown
 I will
- Create an issue
- Write some MD
- Add an assignee and ask them to direct an issue back at me.

**Comment by pernilla-hallgren** [comment]
Bra jobbat! Ska försöka skapa ett issue till då..?! Vi får se om det går :)

**Comment by nazaninpouresmaili** [comment]
Ja, tänkte det kan vara bra att se samma action både från avsändare- och mottagarhållet :)
Lyacka till!

**Comment by pernilla-hallgren** [comment]
Bra tänkt! Jag har skickat ett issue till dig :)

**Comment by nazaninpouresmaili** [comment]
Toppen, då är detta issue löst. Jag stänger detta, och stångar mig genom nästa issue!
