### ISSUE TITLE
Issue testing 

### ISSUE THREAD

**Issue by pernilla-hallgren** [pernilla-hallgren/github-test#5]
# **Issue testing**

## Making my first issue in Markdown

* Adding an issue back at Nazanin and asking her to add a "juice.txt"  file to our githud-test repository. 
* Also make a new pull-request back at me so we can merge it after

**Comment by nazaninpouresmaili** [comment]
Jag har klonat mappen och adderat juice-filen lokalt på min dator, men är osäker på vad jag gör sen för att koppla till den originala mappen som ligger här.. Ska jag köra git init på den klonade mappen? Eller skapar det bara en ny kopia av kalaset?

**Comment by pernilla-hallgren** [comment]
Har du skapat en ny branch?

**Comment by nazaninpouresmaili** [comment]
Nej men alltså när jag skriver git statut får jag återkoppling att "fatal: not a git repository". så jag antar att jag har missat ett steg (en av dom allra första stegen)

**Comment by pernilla-hallgren** [comment]
Skapa en ny branch och öppna sedan upp juice.txt och redigera i den alternativt gör en ny text.txt fil. När du gjort det så kör tu git add filnamn och sedan git commit -m "skriv vad du gjort"  därefter skriver du git status

**Comment by nazaninpouresmaili** [comment]
Men det är något som är vajsing. Jag kan inte "add" heller.
![Uploading Skärmavbild 2020-10-04 kl. 18.32.23.png…]()

**Comment by pernilla-hallgren** [comment]
Om du sen ska skicka tillbaka ändringarna till github så skriv git push -u origin branchnamnet
Detta gör du när du står i den nya branchen du skapat... vi skapar en ny branch eftersom vi inte vill redigera i master.
Sen om du vill gå ur den branchen du skapat så skriver vi git checkout master så kommer du tillbaka

**Comment by pernilla-hallgren** [comment]
okej?! Men om kan du se om du verkligen klonat ner projektet? Kolla i finder

**Comment by nazaninpouresmaili** [comment]
yes

<img width="618" alt="Skärmavbild 2020-10-04 kl  18 32 23" src="https://user-images.githubusercontent.com/70700130/95021276-565d7000-0670-11eb-8ce3-98ab3a00d648.png">

**Comment by pernilla-hallgren** [comment]
Innan du gör git add måste du skapa en ny branch har du gjort det?

**Comment by nazaninpouresmaili** [comment]
Back to basics - Jag står i Guthub-test-master i terminalen. Vad är det allra första jag gör? Jag har alltså bara klonat ner mappen och öppnat den i terminalen.

**Comment by pernilla-hallgren** [comment]
Ok :) 
git checkout -b namn  =skapar en ny branch som du döper till juice
touch juice.txt.  = för att skapa en ny text fil i den nya branchen. (lägg  märke till att master inte längre heter master utan juice)

**Comment by pernilla-hallgren** [comment]
vi juice.txt = för att gå in i den nya text filen du skapat och skriva i den (lägg till lite text där tryck I för insert så du kan skriva i den och sedan esc :wq för att spara och gå ur. 

Nu har vi alltså skapat en nu branch som heter juice samt en ny juice.txt fil

**Comment by nazaninpouresmaili** [comment]
Får samma felmeddelande. att det inte är en git repository

**Comment by pernilla-hallgren** [comment]
mmm ok konstigt vilken länk använde dig av när du klonade ner?  Ser du alla filer om du går in finder?
![Uploading Screenshot 2020-10-04 at 18.43.50.png…]()

**Comment by pernilla-hallgren** [comment]
Vänta tror du måste få in i mappen githud-test när du gör alla stegen.. det är ju den mappen som är ett repository

**Comment by pernilla-hallgren** [comment]
<img width="950" alt="Screenshot 2020-10-04 at 18 50 10" src="https://user-images.githubusercontent.com/70695214/95021650-8574e100-0672-11eb-9efc-a41d31f2e352.png">

**Comment by nazaninpouresmaili** [comment]
Jag laddade nez zip och provade med den. då fick jag dessa felmeddelanden. Men provade nu att skriva git clone och klistra in https adressen under "clone"knappen.  Får då ett jättelångt felmeddelande. Ger upp. Blir så satans ineffektivt att sitta såhär, får ta det irl nästa gång ist.

**Comment by pernilla-hallgren** [comment]
Det är https adressen du klistrar in efter clone. 
Ja, det är svårt att försöka förklara åt båda hållen via chat... :(

**Comment by nazaninpouresmaili** [comment]
SÅJA! Äntligen. Vet inte vad jag gjorde, men nu är vi igång. Jag har skapat en ny branch, lagt till en ny textfil, och addat den. Ska jag commita nu, och sen merga?

**Comment by pernilla-hallgren** [comment]
Grymt!
Efter git add så kör du git commit -m namn.txt
Därefter git push -u origin master (då pushar du upp den till github och där gör du en pull request så kan man kolla den och sedan därifrån merge)

**Comment by nazaninpouresmaili** [comment]
Haha gick händelserna i förväg och mergade och hade mig innan jag pushade skiten, så det ligger en juice redan på mastern. MEN gjorde en juice2 som jag nu har pushat. Vart gör jag pull request? I terminalen det också, eller i Github?

**Comment by pernilla-hallgren** [comment]
Haha det är lugnt det är ju så man lär sig :) gå in i githud och skapa en pull request

**Comment by nazaninpouresmaili** [comment]
Hmm fattar inte hur. Borde inte min nya branch "juice2" synas i listan?

**Comment by pernilla-hallgren** [comment]
den borde ligga i branches? Men ser inga där?
skrev du git push -u origin master   när du står i branchen juice? i terminalen alltså

**Comment by pernilla-hallgren** [comment]
Men jag ser din nya juice.txt i master!! :-)

**Comment by pernilla-hallgren** [comment]
sorry du måste skriva git push -u origin juice

**Comment by pernilla-hallgren** [comment]
det är ju juice branchen du pushar.... jag gjorde det felet tidigare... trodde jag hade lärt mig av de men tydligen inte. Tror jag är lite trött nu :-)

**Comment by nazaninpouresmaili** [comment]
Haha jahaaa ok nu gick det! Ok så då kör jag pull & compare antar jag

**Comment by pernilla-hallgren** [comment]
Nu ser jag din branch :) gå in på branches och sen klicka på new pull request höger om branchen
